name: Deploy Main Site

on:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: main-deploy
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Validate content
      run: |
        echo "Validating site content..."
        
        # Check required files exist
        required_files=("docs/index.md" "mkdocs.yml" "docs/community/coaches.md")
        for file in "${required_files[@]}"; do
          if [ ! -f "$file" ]; then
            echo "ERROR: Required file missing: $file"
            exit 1
          else
            echo "Found: $file"
          fi
        done
        
        # Validate coach data structure
        if grep -q "<ul>" docs/community/coaches.md; then
          echo "Coaches file has proper HTML structure"
        else
          echo "Warning: Coaches file may be missing HTML structure"
        fi
        
        echo "Content validation completed"
    
    - name: Build site
      run: |
        echo "Building main site..."
        mkdocs build --strict
        
        # Add build timestamp
        echo "<!-- Built: $(date -u +'%Y-%m-%d %H:%M:%S UTC') -->" >> site/index.html
        
        echo "Site built successfully"
        echo "Site size: $(du -sh site)"
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        keep_files: true
        enable_jekyll: false
        commit_message: 'Deploy main site: ${{ github.sha }}'
        force_orphan: false
        cname: # Add your custom domain here if you have one
    
    - name: Verify deployment
      run: |
        echo "Main site deployed successfully!"
        echo "Available at: https://icpc-menofia.github.io/menofia-roadmap/"
        echo "Deploy commit: ${{ github.sha }}"
        echo "Deploy time: $(date -u +'%Y-%m-%d %H:%M:%S UTC')" 